src/main/java/com/petservice/main/common/config/SecurityConfig.java, src/main/java/com/petservice/main/user/controller/UserController.java, src/main/java/com/petservice/main/user/database/dto/CustomOAuth2UserDetail.java, src/main/java/com/petservice/main/user/database/dto/CustomUserDetails.java, src/main/java/com/petservice/main/user/database/dto/LoginRequest.java, src/main/java/com/petservice/main/user/database/dto/RefreshTokenDTO.java, src/main/java/com/petservice/main/user/database/dto/TokenRefreshRequest.java, src/main/java/com/petservice/main/user/database/dto/TokenRefreshResponse.java, src/main/java/com/petservice/main/user/database/dto/UserDTO.java, src/main/java/com/petservice/main/user/database/entity/RefreshToken.java, src/main/java/com/petservice/main/user/database/entity/Role.java, src/main/java/com/petservice/main/user/database/entity/User.java, src/main/java/com/petservice/main/user/database/mapper/TokenMapper.java, src/main/java/com/petservice/main/user/database/mapper/UserMapper.java, src/main/java/com/petservice/main/user/database/repository/RefreshTokenRepository.java, src/main/java/com/petservice/main/user/database/repository/UserRepository.java, src/main/java/com/petservice/main/user/jwt/JwtFilter.java, src/main/java/com/petservice/main/user/service/Interface/CustomUserServiceInterface.java, src/main/java/com/petservice/main/user/service/Interface/RefreshTokenServiceInterface.java, src/main/java/com/petservice/main/user/service/Oauth2Service.java, src/main/java/com/petservice/main/user/service/Oauth2SuccessHandler.java, src/main/java/com/petservice/main/user/service/RefreshTokenService.java, src/main/java/com/petservice/main/user/service/UserService.java
=> User Database package move

frontend/src/App.jsx, frontend/src/common/Api/Api.jsx, frontend/src/common/Api/RefreshApi.jsx, frontend/src/common/Ui/PasswordInput.jsx, frontend/src/user/Form/DeleteForm.jsx, frontend/src/user/Form/LoginForm.jsx, frontend/src/user/Form/RegisterForm.jsx, frontend/src/user/Form/UpdateForm.jsx, frontend/src/user/Page/DeletePage.jsx, frontend/src/user/Page/UpdatePage.jsx, frontend/src/user/Page/UserInfoPage.jsx, frontend/src/user/component/DeleteButton.jsx, frontend/src/user/component/LogoutButton.jsx, frontend/src/user/component/UpdateButton.jsx, frontend/src/user/component/UserInfo.jsx, src/main/java/com/petservice/main/common/config/SecurityConfig.java, src/main/java/com/petservice/main/user/controller/UserController.java, src/main/java/com/petservice/main/user/database/dto/CustomUserDetails.java, src/main/java/com/petservice/main/user/database/entity/UserType.java, src/main/java/com/petservice/main/user/database/repository/UserRepository.java, src/main/java/com/petservice/main/user/jwt/JwtFilter.java, src/main/java/com/petservice/main/user/jwt/JwtService.java, src/main/java/com/petservice/main/user/service/Interface/CustomUserServiceInterface.java, src/main/java/com/petservice/main/user/service/Oauth2SuccessHandler.java, src/main/java/com/petservice/main/user/service/UserService.java, src/main/resources/application.yml
회원 탈퇴 나 수정 관련 API 코드 작성 및 UI변경, React 라우터 링크 변경, 오류 일부 수정
=> 회원 관련 기능 추가

src/main/java/com/petservice/main/business/database/entity/BusinessStatus.java, src/main/java/com/petservice/main/business/database/entity/PetBusiness.java, src/main/java/com/petservice/main/business/database/entity/PetBusinessType.java, src/main/java/com/petservice/main/business/database/entity/Varification.java, src/main/java/com/petservice/main/common/database/entity/TimeEntity.java, src/main/java/com/petservice/main/user/database/entity/Address.java, src/main/java/com/petservice/main/user/database/entity/Bookmark.java, src/main/java/com/petservice/main/user/database/entity/BookmarkType.java, src/main/java/com/petservice/main/user/database/entity/Gender.java, src/main/java/com/petservice/main/user/database/entity/Pet.java, src/main/java/com/petservice/main/user/database/entity/User.java
사용자, 사업자, 사업자 타입, 애완동물, 북마크, 주소 엔티티와 관련된 열거형 추가
=> 사용자와 사업자 관련 엔티티, 열거형 추가

src/main/java/com/petservice/main/business/database/dto/PetBusinessDTO.java, src/main/java/com/petservice/main/business/database/dto/PetBusinessTypeDTO.java, src/main/java/com/petservice/main/business/database/mapper/PetBusinessMapper.java, src/main/java/com/petservice/main/business/database/mapper/PetBusinessTypeMapper.java, src/main/java/com/petservice/main/business/database/repository/PetBusinessRepository.java, src/main/java/com/petservice/main/business/database/repository/PetBusinessTypeRepository.java, src/main/java/com/petservice/main/qna/service/Interface/QnaServiceInterface.java, src/main/java/com/petservice/main/qna/service/QnaService.java, src/main/java/com/petservice/main/user/database/dto/AddressDTO.java, src/main/java/com/petservice/main/user/database/dto/BookmarkDTO.java, src/main/java/com/petservice/main/user/database/dto/PetDTO.java, src/main/java/com/petservice/main/user/database/dto/UserDTO.java, src/main/java/com/petservice/main/user/database/mapper/AddressMapper.java, src/main/java/com/petservice/main/user/database/mapper/BookmarkMapper.java, src/main/java/com/petservice/main/user/database/mapper/PetMapper.java, src/main/java/com/petservice/main/user/database/mapper/UserMapper.java, src/main/java/com/petservice/main/user/database/repository/AddressRepository.java, src/main/java/com/petservice/main/user/database/repository/BookmarkRepository.java, src/main/java/com/petservice/main/user/database/repository/PetRepository.java
새로 추가한 Entity에 대한 DTO, Mapper 생성, 일부 qna Service Interface, qna Service class 생성
=>  DTO, Mapper 신규 작성, 일부 Service Interface, class 생성

src/main/java/com/petservice/main/qna/database/entity/QnaAnswer.java, src/main/java/com/petservice/main/qna/database/entity/QnaPost.java
QnaPost and QnaAnswer entities
=> add QnaPost and QnaAnswer entities

src/main/java/com/petservice/main/qna/database/dto/QnaAnswerDTO.java, src/main/java/com/petservice/main/qna/database/dto/QnaPostDTO.java, src/main/java/com/petservice/main/qna/database/entity/QnaAnswer.java, src/main/java/com/petservice/main/qna/database/entity/QnaPost.java, src/main/java/com/petservice/main/qna/database/mapper/QnaAnswerMapper.java, src/main/java/com/petservice/main/qna/database/mapper/QnaPostMapper.java, src/main/java/com/petservice/main/qna/database/repository/QnaAnswerRepository.java, src/main/java/com/petservice/main/qna/database/repository/QnaPostRepository.java, src/main/java/com/petservice/main/user/database/dto/UserDTO.java, src/main/java/com/petservice/main/user/database/entity/User.java, src/main/java/com/petservice/main/user/database/mapper/UserMapper.java
Qna Entity 일부 수정, Qna와 관련된 mapper, DTO, Repository를 추가, User의 mapper, dto 부분 수정
=> Qna mapper, DTO, Repository add

frontend/src/common/Context/UserContext.jsx, frontend/src/common/Ui/Button.jsx, frontend/src/user/Form/RegisterForm.jsx, frontend/src/user/component/UserInfo.jsx, frontend/src/user/component/UserInfoDetail.jsx, src/main/java/com/petservice/main/business/database/dto/PetBusinessDTO.java, src/main/java/com/petservice/main/business/database/mapper/PetBusinessMapper.java, src/main/java/com/petservice/main/business/database/mapper/PetBusinessTypeMapper.java, src/main/java/com/petservice/main/business/database/repository/PetBusinessRepository.java, src/main/java/com/petservice/main/business/service/BusinessService.java, src/main/java/com/petservice/main/business/service/Interface/BusinessServiceInterface.java, src/main/java/com/petservice/main/qna/database/mapper/QnaPostMapper.java, src/main/java/com/petservice/main/user/controller/UserController.java, src/main/java/com/petservice/main/user/database/mapper/UserMapper.java, src/main/java/com/petservice/main/user/database/repository/UserRepository.java, src/main/java/com/petservice/main/user/service/UserService.java
새로운 Entity, DTO, mapper, repository 추가와 User Entity, DTO, Mapper 수정에 따른 회원 가입과 회원 정보, 세부 정보 보기 기능 수정, 리스트 변환은 제외한 BasicMapper 일부 추가
=> entity, dto, mapper, repository 추가에 따른 코드 수정 및 몇몇 mapper 추가

src/main/java/com/petservice/main/business/database/dto/ReservationDTO.java, src/main/java/com/petservice/main/business/database/entity/Reservation.java, src/main/java/com/petservice/main/business/database/entity/ReservationStatus.java, src/main/java/com/petservice/main/payment/database/dto/PaymentDTO.java, src/main/java/com/petservice/main/payment/database/entity/Payment.java, src/main/java/com/petservice/main/payment/database/entity/PaymentStatus.java, src/main/java/com/petservice/main/payment/database/entity/RefundStatus.java
feat: add Payment entity and DTO
Reservation 엔티티가 아직 구현되지 않아서 Payment 쪽에서 import 에러가 납니다.
추후 Reservation이 추가되면 자동으로 해결될 예정입니다.
=> add Payment

frontend/src/user/Form/UpdateForm.jsx, frontend/src/user/component/UserInfo.jsx, src/main/java/com/petservice/main/business/database/entity/PetBusinessRoom.java, src/main/java/com/petservice/main/business/database/entity/PetReservation.java, src/main/java/com/petservice/main/business/database/entity/Reservation.java, src/main/java/com/petservice/main/business/database/repository/ReservationRepository.java, src/main/java/com/petservice/main/review/database/dto/ReviewDTO.java, src/main/java/com/petservice/main/review/database/entity/Review.java, src/main/java/com/petservice/main/review/database/mapper/ReviewMapper.java, src/main/java/com/petservice/main/review/database/repository/ReviewRepository.java, src/main/java/com/petservice/main/user/database/entity/User.java
=> 일부 엔티티 연관 수정, ui 구현중

frontend/src/common/Api/ApiService.jsx, frontend/src/common/Ui/CustomLabel.jsx, frontend/src/user/Form/UpdateForm.jsx, frontend/src/user/component/UserProviderInfo.jsx, src/main/java/com/petservice/main/business/database/dto/PetBusinessDTO.java, src/main/java/com/petservice/main/business/database/entity/PetBusiness.java, src/main/java/com/petservice/main/user/controller/UserController.java
사업자 관련 Entity와 DTO에 예약, 룸 관련 연관관계를 추가하였으며, 미쳐 추가하지 않았던 일부 jsx 파일(api를 정리한 파일, 커스텀 태그, 사업자 정보 컴포넌트)를 추가하였고, 회원 수정 관련 UI 도 수정
=> 일부 jsx 파일 추가 및 회원 수정 관련 UI 수정  

src/main/java/com/petservice/main/payment/database/mapper/PaymentMapper.java
=> Add PaymentMapper

src/main/java/com/petservice/main/business/database/dto/PetBusinessDTO.java, src/main/java/com/petservice/main/business/database/dto/PetBusinessRoomDTO.java, src/main/java/com/petservice/main/business/database/dto/ReservationDTO.java, src/main/java/com/petservice/main/business/database/entity/PetBusiness.java, src/main/java/com/petservice/main/business/database/entity/Reservation.java, src/main/java/com/petservice/main/business/database/mapper/PetBusinessMapper.java, src/main/java/com/petservice/main/business/database/mapper/PetBusinessRoomMapper.java, src/main/java/com/petservice/main/business/database/mapper/PetReservationMapper.java, src/main/java/com/petservice/main/business/database/mapper/ReservationMapper.java, src/main/java/com/petservice/main/business/database/repository/PetBusinessRoomRepository.java, src/main/java/com/petservice/main/business/database/repository/PetReservationRepository.java, src/main/java/com/petservice/main/payment/database/dto/PaymentDTO.java, src/main/java/com/petservice/main/payment/database/mapper/PaymentMapper.java, src/main/java/com/petservice/main/payment/database/repository/PaymentRepository.java, src/main/java/com/petservice/main/qna/database/dto/QnaAnswerDTO.java, src/main/java/com/petservice/main/qna/database/entity/QnaAnswer.java, src/main/java/com/petservice/main/qna/database/entity/QnaPost.java, src/main/java/com/petservice/main/qna/database/mapper/QnaAnswerMapper.java, src/main/java/com/petservice/main/qna/database/mapper/QnaPostMapper.java, src/main/java/com/petservice/main/user/database/dto/UserDTO.java, src/main/java/com/petservice/main/user/database/entity/Pet.java, src/main/java/com/petservice/main/user/database/mapper/BookmarkMapper.java, src/main/java/com/petservice/main/user/database/mapper/PetMapper.java, src/main/java/com/petservice/main/user/database/mapper/UserMapper.java
서비스의 기반인 DTO, Entity, Repository, Mapper 작성 및 검사 완료
=> database 관련 클래스 검사 완료

frontend/src/common/Context/UserContext.jsx, frontend/src/user/Form/RegisterForm.jsx, frontend/src/user/Form/UpdateForm.jsx, frontend/src/user/component/UserInfoDetail.jsx, src/main/java/com/petservice/main/user/service/Oauth2Service.java
구글 회원가입에서 추가적인 컬럼 설정(일반회원으로만 가입가능), 회원 포인트 관련 frontend 수정
=> 구글 회원 가입 로직 수정

frontend/src/user/Form/RegisterForm.jsx, frontend/src/user/Form/UpdateForm.jsx, src/main/java/com/petservice/main/user/controller/UserController.java, src/main/java/com/petservice/main/user/database/repository/UserRepository.java, src/main/java/com/petservice/main/user/service/Interface/CustomUserServiceInterface.java, src/main/java/com/petservice/main/user/service/Oauth2Service.java, src/main/java/com/petservice/main/user/service/UserService.java
회원 관련 Service 출력 Entity에서 DTO로 변경 그리고 그에 따른 일부 Controller, 다른 Service 로직 변경, 일부 최적화(쿼리 감소), UI 변경
=> 코드 리펙터링 및 일부 UI 수정

src/main/java/com/petservice/main/qna/controller/QnaAnswerController.java, src/main/java/com/petservice/main/qna/controller/QnaPostController.java, src/main/java/com/petservice/main/qna/database/repository/QnaAnswerRepository.java, src/main/java/com/petservice/main/qna/database/repository/QnaPostRepository.java, src/main/java/com/petservice/main/qna/service/Interface/QnaServiceInterface.java, src/main/java/com/petservice/main/qna/service/QnaService.java, src/main/java/com/petservice/main/qna/service/answer/QnaAnswerService.java, src/main/java/com/petservice/main/qna/service/answer/QnaAnswerServiceInterface.java, src/main/java/com/petservice/main/qna/service/post/QnaPostService.java, src/main/java/com/petservice/main/qna/service/post/QnaPostServiceInterface.java
=> Add QnaPost

frontend/src/App.jsx, frontend/src/common/Api/RefreshApi.jsx, frontend/src/common/ErrorPage/CustomErrorPage.jsx, frontend/src/user/Form/RegisterForm.jsx, src/main/java/com/petservice/main/business/database/entity/PetBusiness.java, src/main/java/com/petservice/main/business/service/Interface/PetBusinessServiceInterface.java, src/main/java/com/petservice/main/business/service/Interface/PetBusinessTypeServiceInterface.java, src/main/java/com/petservice/main/business/service/PetBusinessService.java, src/main/java/com/petservice/main/business/service/PetBusinessTypeService.java, src/main/java/com/petservice/main/common/exception/ApiExceptionHandler.java, src/main/java/com/petservice/main/user/controller/UserController.java, src/main/java/com/petservice/main/user/service/Interface/CustomUserServiceInterface.java, src/main/java/com/petservice/main/user/service/UserService.java
UserDTO 값 검증 강화, PetBusiness 수정, 커스텀 오류 화면 통일, 관리자 가입 메소드(서비스) 추가
=> 일부 엔티티 수정, 회원가입 검증 강화, 일부 컴포넌트 삭제

src/main/java/com/petservice/main/business/controller/PetBusinessTypeController.java, src/main/java/com/petservice/main/business/database/entity/PetBusinessType.java, src/main/java/com/petservice/main/business/database/repository/PetBusinessRepository.java, src/main/java/com/petservice/main/business/database/repository/PetBusinessTypeRepository.java, src/main/java/com/petservice/main/business/service/Interface/PetBusinessTypeServiceInterface.java, src/main/java/com/petservice/main/business/service/PetBusinessTypeService.java, src/main/java/com/petservice/main/user/service/UserService.java
펫 사업자 타입 서비스 메소드 추가, 리포지토리 메소드 추가 및 일부 엔티티, 로그 수정
=> PetBusinessType Service method add

src/main/java/com/petservice/main/business/controller/PetBusinessTypeController.java, src/main/java/com/petservice/main/business/service/Interface/PetBusinessTypeServiceInterface.java, src/main/java/com/petservice/main/business/service/PetBusinessTypeService.java
=> Pet Business Type Controller

src/main/java/com/petservice/main/business/controller/PetBusinessController.java, src/main/java/com/petservice/main/business/service/Interface/PetBusinessServiceInterface.java, src/main/java/com/petservice/main/business/service/PetBusinessService.java
단순 애완동물 사업자 관련 Service Interface method 추가
=> Pet Service Interface method add

frontend/src/common/Api/Api.jsx, frontend/src/common/Api/ApiService.jsx, frontend/src/common/Css/common.css, frontend/src/common/Ui/Modal.jsx, src/main/java/com/petservice/main/pet/controller/PetController.java
일단 qna, pet, businesstype 관련 jsx 빈 파일 생성 및 최근 작성된 api 사용을 위한 React API 쪽 추가 작성 및 유연한 구현을 위한 모달창 컴포넌트 구현
=> Qna 기능, 애완동물 기능, 애완동물 사업자 타입 관련 기능 구현을 위한 jsx 파일 생성

frontend/src/common/Css/common.css, frontend/src/qna/Component/PostList.jsx, frontend/src/qna/Form/PostRegisterForm.jsx
frontend-post list page % registerform
=> feat(qna-frontend):post list page & register form

frontend/src/pet/Component/Pet.jsx, frontend/src/pet/Component/PetDeleteButton.jsx, frontend/src/pet/Component/PetList.jsx, frontend/src/pet/Form/PetRegisterForm.jsx, frontend/src/pet/Form/PetUpdateForm.jsx, frontend/src/pet/Page/PetManagePage.jsx
=> feat: Add Pet components, forms, and page

frontend/src/App.jsx, frontend/src/common/Api/ApiService.jsx, frontend/src/pet/Component/Pet.jsx, frontend/src/pet/Component/PetList.jsx, frontend/src/pet/Form/PetRegisterForm.jsx, frontend/src/pet/Form/PetUpdateForm.jsx, frontend/src/pet/Page/PetManagePage.jsx, frontend/src/user/component/UserInfo.jsx, src/main/java/com/petservice/main/pet/controller/PetController.java, src/main/java/com/petservice/main/pet/service/PetServiceImpl.java, src/main/java/com/petservice/main/pet/service/PetServiceInterface.java, src/main/java/com/petservice/main/user/database/dto/PetDTO.java, src/main/java/com/petservice/main/user/database/entity/Pet.java, src/main/java/com/petservice/main/user/database/mapper/PetMapper.java, src/main/java/com/petservice/main/user/service/UserService.java
펫 프론트 엔드 컴포넌트에서 누락된 부분이나 api가 정상적으로 동작하지 않는 부분 수정, 그리고 일부 컨트롤러나 서비스 로직 수정
=> 펫 관련 기능 오류 수정

src/main/java/com/petservice/main/business/controller/PetBusinessController.java, src/main/java/com/petservice/main/business/database/dto/SearchRequest.java, src/main/java/com/petservice/main/business/service/Interface/NaverSearchServiceInterface.java, src/main/java/com/petservice/main/business/service/Interface/PetBusinessServiceInterface.java, src/main/java/com/petservice/main/business/service/NaverSearchService.java, src/main/java/com/petservice/main/business/service/PetBusinessService.java, src/main/java/com/petservice/main/user/database/dto/AddressDTO.java, src/main/java/com/petservice/main/user/database/entity/Address.java, src/main/java/com/petservice/main/user/database/mapper/AddressMapper.java, src/main/java/com/petservice/main/user/database/repository/AddressRepository.java, src/main/java/com/petservice/main/user/service/AddressService.java, src/main/java/com/petservice/main/user/service/Interface/AddressServiceInterface.java
일반 애완동물 서비스 사업자 조회, Naver 지역 검색 api를 이용한 실제 사업자 조회 api 구현 관련 Service mehtod 수정을 통한 최적화,
address entity 컬럼 추가, Service, Repository method 추가 
=> 애완동물 서비스 사업자 조회 api 구현 및 일부 수정

src/main/java/com/petservice/main/api/database/dto/BnsVLRequest.java, src/main/java/com/petservice/main/api/database/dto/BnsVLResponse.java, src/main/java/com/petservice/main/api/database/dto/BnsVLResult.java, src/main/java/com/petservice/main/api/database/dto/NaverApiResponse.java, src/main/java/com/petservice/main/api/database/dto/NaverPlaceItem.java, src/main/java/com/petservice/main/api/database/dto/NaverSearchRequest.java, src/main/java/com/petservice/main/api/database/entity/BnsVLRequestEntity.java, src/main/java/com/petservice/main/api/database/entity/RequestStatus.java, src/main/java/com/petservice/main/api/database/mapper/BnsVLRequestMapper.java, src/main/java/com/petservice/main/api/database/repository/BnsVLRequestRepository.java, src/main/java/com/petservice/main/api/service/BnsVLService.java, src/main/java/com/petservice/main/api/service/Interface/BnsVLServiceInterface.java, src/main/java/com/petservice/main/api/service/Interface/NaverSearchServiceInterface.java, src/main/java/com/petservice/main/api/service/NaverSearchService.java, src/main/java/com/petservice/main/business/controller/PetBusinessController.java, src/main/java/com/petservice/main/business/service/Interface/PetBusinessServiceInterface.java
business 패키지의 클래스 파일이 너무 많아서 api 패키지 따로 만들어 정리(네이버 지역 검색 api, 사업자 진위 확인 api), 사업자 인증 api를 사용하기 위한 각종 DTO, Entity(요청을 DB에 저장해야한다), Repository, Service 클래스 생성 및 일부 구현
=> 일부 클래스 이동 및 사업자 진위 확인 api 사용 준비

frontend/src/qna/Component/AnswerDeleteButton.jsx, frontend/src/qna/Component/AnswerList.jsx, frontend/src/qna/Component/PostDeleteButton.jsx, frontend/src/qna/Form/AnswerRegisterForm.jsx, frontend/src/qna/Form/AnswerUpdateForm.jsx, frontend/src/qna/Form/PostRegisterForm.jsx, frontend/src/qna/Form/PostUpdateForm.jsx, frontend/src/qna/Page/PostRegisterPage.jsx, frontend/src/qna/Page/QnaDetailPage.jsx, frontend/src/qna/Page/QnaListPage.jsx, frontend/src/qna/Page/QnaPage.jsx
=> qna-frontend

src/main/java/com/petservice/main/business/database/dto/PetBusinessRoomDTO.java, src/main/java/com/petservice/main/business/database/dto/PetReservationDTO.java, src/main/java/com/petservice/main/business/database/dto/ReservationDTO.java, src/main/java/com/petservice/main/business/database/dto/ReservationRequest.java, src/main/java/com/petservice/main/business/database/mapper/PetBusinessRoomMapper.java, src/main/java/com/petservice/main/business/database/mapper/PetReservationMapper.java, src/main/java/com/petservice/main/business/database/mapper/ReservationMapper.java, src/main/java/com/petservice/main/business/database/repository/PetBusinessRepository.java, src/main/java/com/petservice/main/business/database/repository/PetBusinessRoomRepository.java, src/main/java/com/petservice/main/business/database/repository/PetReservationRepository.java, src/main/java/com/petservice/main/business/database/repository/ReservationRepository.java, src/main/java/com/petservice/main/business/service/Interface/PetBusinessRoomServiceInterface.java, src/main/java/com/petservice/main/business/service/Interface/PetReservationServiceInterface.java, src/main/java/com/petservice/main/business/service/Interface/ReservationServiceInterface.java, src/main/java/com/petservice/main/business/service/PetBusinessRoomService.java, src/main/java/com/petservice/main/business/service/PetReservationService.java, src/main/java/com/petservice/main/business/service/ReservationService.java
애완동물 서비스 예약 관련 crud, 검증 Service method 구현, 애완동물 사업자 방 조회 Service method 구현, 그 외 관련된 DTO, Mapper 변경 및 Repository method 작성
=> 서비스 예약, 애완동물 사업자 방 관련 메소드 작성

src/main/java/com/petservice/main/review/controller/ReviewController.java, src/main/java/com/petservice/main/review/database/repository/ReviewRepository.java, src/main/java/com/petservice/main/review/service/ReviewService.java, src/main/java/com/petservice/main/review/service/ReviewServiceImpl.java
=> feat: review CRUD 기능 구현

frontend/src/business/Component/Business.jsx, frontend/src/business/Component/BusinessList.jsx, frontend/src/business/Component/BusinessRoom.jsx, frontend/src/business/Component/BusinessRoomList.jsx, frontend/src/business/Form/ReservationForm.jsx, frontend/src/business/Page/BusinessManagePage.jsx, frontend/src/business/Page/BusinessSearchPage.jsx, frontend/src/common/Api/Api.jsx, frontend/src/common/Api/ApiService.jsx, frontend/src/pet/Component/PetList.jsx, frontend/src/pet/Page/PetManagePage.jsx, frontend/src/qna/Component/AnswerList.jsx, frontend/src/user/Form/BusinessValidationForm.jsx, frontend/src/user/component/BusinessValidationButton.jsx, frontend/src/user/component/UserProviderInfo.jsx, src/main/java/com/petservice/main/api/ScheduledValidation.java, src/main/java/com/petservice/main/api/controller/ApiController.java, src/main/java/com/petservice/main/api/database/dto/BnsVLRequestList.java, src/main/java/com/petservice/main/api/database/entity/BnsVLRequestEntity.java, src/main/java/com/petservice/main/api/database/mapper/BnsVLRequestMapper.java, src/main/java/com/petservice/main/api/service/BnsVLService.java, src/main/java/com/petservice/main/api/service/Interface/BnsVLServiceInterface.java, src/main/java/com/petservice/main/business/service/PetBusinessService.java, src/main/java/com/petservice/main/user/database/repository/UserRepository.java
사업자 인증에서 인코딩 문제, 메일 전송 문제와 관련된 버그를 수정하였고, 서비스 시작 기준 1시간 마다 db에 저장된 사업자 인증 요청을 자동으로 처리하도록 변경,
일부 사업자, 예약, 사업자 인증 컴포넌트 구현 및 파일 생성
=> 사업자 인증 관련 오류 수정 및 사업자, 예약 관련 컴포넌트 일부 구현

frontend/src/review/Component/ReviewDeleteButton.jsx, frontend/src/review/Form/ReviewRegisterForm.jsx, frontend/src/review/Form/ReviewUpdateForm.jsx, frontend/src/review/Page/ReviewDetailPage.jsx, frontend/src/review/Page/ReviewListPage.jsx, frontend/src/review/Page/ReviewPage.jsx, frontend/src/review/Page/ReviewRegisterPage.jsx
=> feat(review): complete frontend review CRUD functionality

frontend/src/App.jsx, frontend/src/business/Component/Reservation.jsx, frontend/src/business/Component/ReservationList.jsx, frontend/src/business/Form/ReservationForm.jsx, frontend/src/business/Page/BusinessManagePage.jsx, frontend/src/business/Page/BusinessSearchPage.jsx, frontend/src/common/Api/Api.jsx, frontend/src/common/Api/ApiService.jsx, frontend/src/common/Ui/Modal.jsx, frontend/src/main.jsx, frontend/src/pay/Component/Pay.jsx, frontend/src/pay/Component/PayList.jsx, frontend/src/user/component/UserInfo.jsx, frontend/src/user/component/UserInfoDetail.jsx, frontend/src/user/component/UserProviderInfo.jsx, src/main/java/com/petservice/main/api/service/NaverSearchService.java, src/main/java/com/petservice/main/business/controller/PetBusinessController.java, src/main/java/com/petservice/main/business/controller/PetBusinessRoomController.java, src/main/java/com/petservice/main/payment/database/dto/PaymentDTO.java, src/main/java/com/petservice/main/user/service/AddressService.java
예약 관련 컴포넌트, 룸 관련 컴포넌트 생성 및 개선, 
사업자 검색 페이지 컴포넌트 구현, 사업자 관리 페이지 컴포넌트 일부 구현,
결제 관련 컴포넌트 일부 구현,
Api, ApiService 일부 추가 작성,
모달 창 개선,
몇몇 컴포넌트 부트스트랩 반영,
백엔드 쪽 몇몇 버그 수정
=> 프론트엔드 컴포넌트 추가, 몇몇 오류 수정

frontend/src/App.css, frontend/src/App.jsx, frontend/src/common/Ui/Footer.jsx, frontend/src/common/Ui/Header.jsx, frontend/src/index.css
=> frontend-mainpage Header Footer

frontend/src/common/Page/HomePage.jsx
=> frontend-HomePage

frontend/src/common/Ui/ServicesSection.jsx
=> frontend-ServicesSection

frontend/index.html, frontend/src/App.css, frontend/src/common/Ui/Header.jsx
=> style: 헤더 로고 구글 폰트 및 컬러 효과 적용

frontend/src/App.css, frontend/src/common/Ui/Footer.jsx
=> style: 푸터 레이아웃 및 저작권 문구 추가

frontend/src/business/Component/BusinessRoomList.jsx, frontend/src/business/Component/Reservation.jsx, frontend/src/business/Component/ReservationList.jsx, frontend/src/business/Form/ReservationForm.jsx, frontend/src/business/Form/RoomRegisterForm.jsx, frontend/src/business/Form/RoomUpdateForm.jsx, frontend/src/business/Page/BusinessManagePage.jsx, frontend/src/pay/Component/PayList.jsx
사업자 관리 페이지, 사업자 방 리스트, 예약, 예약 리스트, 예약 폼, 결제 리스트 컴포넌트 수정,
사업자 방 등록, 수정 폼 컴포넌트 생성
=> 몇몇 프론트엔드 컴포넌트 추가 및 수정

frontend/src/common/Ui/Header.jsx
헤더 로고 이름 pethotel -> petstory로 변경
=> chore: 헤더 로고 이름 변경

frontend/src/App.css, frontend/src/common/Ui/Header.jsx
=> chore: 헤더 background color 푸터와 통일

frontend/src/App.css
=> style: 푸터가 메인 콘텐츠를 덮지 않도록 레이아웃 수정

frontend/src/App.css, frontend/src/common/Page/HomePage.jsx
=> style: 홈 컨테이너 배경색을 헤더·푸터와 어울리게 변경

frontend/src/App.jsx
=> style: 푸터가 항상 하단에 위치하도록 레이아웃 수정

frontend/package.json, frontend/src/bookmark/Bookmark.jsx, frontend/src/bookmark/BookmarkApi.jsx, frontend/src/bookmark/BookmarkList.jsx, frontend/src/user/Page/UserInfoPage.jsx
style: 북마크 컴포넌트 UI 개선 및 스타일 적용 
이제 qna와 연결 예정 
=> style: 북마크 컴포넌트 UI 개선 및 스타일 적용 (이것먼저 커밋 푸시 후 qna와 연결 예정)

frontend/src/App.css
update CSS to fix footer at the bottom
=> style: update CSS to fix footer at the bottom

frontend/src/common/Api/Api.jsx, frontend/src/common/Api/ApiService.jsx, frontend/src/user/Form/RegisterForm.jsx, frontend/src/user/Form/UpdateForm.jsx, frontend/src/user/component/UserProviderInfo.jsx, src/main/java/com/petservice/main/business/controller/PetBusinessTypeController.java, src/main/java/com/petservice/main/business/service/PetBusinessService.java, src/main/java/com/petservice/main/common/config/SecurityConfig.java, src/main/java/com/petservice/main/payment/service/PaymentService.java, src/main/java/com/petservice/main/user/service/UserService.java
회원가입, 회원 정보 수정에 사업자 타입 관련 기능이 잘 동작하도록 수정, 몇몇 api 함수 추가 
=> 사업자 타입 관련 기능 수정 및 프론트엔드 수정

frontend/src/common/Context/UserContext.jsx, frontend/src/qna/Page/QnaDetailPage.jsx, frontend/src/user/component/BookmarkButton.jsx
Add bookmark (heart) button and toggle functionality to QnA detail page
=> feat: Add bookmark (heart) button and toggle functionality to QnA detail page

frontend/src/common/Ui/Header.jsx
add user icon button for MyPage in header with responsive design
=> feat: add user icon button for MyPage in header with responsive design

frontend/index.html, frontend/src/common/Api/ApiService.jsx, frontend/src/common/Context/UserContext.jsx, frontend/src/pay/Form/PaymentForm.jsx, frontend/src/qna/Page/QnaDetailPage.jsx
=> 북마크 관련 오류 수정

frontend/src/business/Component/Reservation.jsx, frontend/src/business/Component/ReservationList.jsx, frontend/src/common/Api/Api.jsx, src/main/java/com/petservice/main/business/controller/ReservationController.java, src/main/java/com/petservice/main/business/service/Interface/ReservationServiceInterface.java, src/main/java/com/petservice/main/business/service/ReservationService.java
=> 예약 관련 오류 수정

frontend/src/App.jsx, frontend/src/business/Form/ReservationUpdateForm.jsx, frontend/src/business/Page/UserReservationManagePage.jsx, frontend/src/common/Api/ApiService.jsx, frontend/src/user/component/UserInfo.jsx, src/main/java/com/petservice/main/business/controller/PetBusinessRoomController.java, src/main/java/com/petservice/main/business/controller/PetReservationController.java, src/main/java/com/petservice/main/business/controller/ReservationController.java, src/main/java/com/petservice/main/business/database/dto/ReservationDTO.java, src/main/java/com/petservice/main/business/database/mapper/ReservationMapper.java, src/main/java/com/petservice/main/business/database/repository/PetBusinessRoomRepository.java, src/main/java/com/petservice/main/business/service/Interface/PetBusinessRoomServiceInterface.java, src/main/java/com/petservice/main/business/service/Interface/PetReservationServiceInterface.java, src/main/java/com/petservice/main/business/service/PetBusinessRoomService.java, src/main/java/com/petservice/main/business/service/PetReservationService.java, src/main/java/com/petservice/main/business/service/ReservationService.java
사용자 예약 관리 페이지, 사용자 예약 수정 폼 컴포넌트 작성 및 기타 로직 오류 수정
=> 예약 관련 컴포넌트 추가 및 오류 수정

frontend/src/qna/Component/AnswerList.jsx, frontend/src/qna/Form/AnswerRegisterForm.jsx, frontend/src/qna/Page/QnaDetailPage.jsx, frontend/src/qna/Page/QnaListPage.jsx
=> 질문 답변 기능 UI 개선 및 구조 리팩토링

frontend/src/App.jsx, frontend/src/common/Context/UserContext.jsx, frontend/src/common/Page/AboutPage.jsx, frontend/src/common/Page/ContactPage.jsx, frontend/src/common/Ui/Header.jsx, src/main/resources/static/index.html
feat: header login/logout button
=> feat: header login/logout button

frontend/src/qna/Component/AnswerList.jsx, frontend/src/qna/Form/AnswerUpdateForm.jsx, frontend/src/qna/Page/QnaDetailPage.jsx, frontend/src/qna/Page/QnaListPage.jsx
=> feat: Q&A 채택 기능 추가 및 UI 개선

frontend/src/App.css, frontend/src/common/Ui/Header.jsx, frontend/src/index.css, src/main/resources/static/index.html
헤더 UI 전면 개선 및 통합 리팩토링
- 네비 메뉴 활성화/비활성화 스타일 개선 (브랜드 컬러 적용)
- Services 드롭다운(About, Contact) 활성화 표시 및 hover 효과 추가
- 검색창에 오렌지색 돋보기 아이콘 적용 및 포커스 효과 강화
- 로그인/로그아웃 버튼 스타일 및 동작 개선
- 코드 정리 및 불필요한 클래스 제거, 접근성 향상
로그인 되지 않은 상태에서 reservation,search,type은 클릭시 오류페이지로 이동돼서 버튼 효과 적용되지 않음
=> feat: 헤더 UI 개선, 네비/드롭다운/검색 스타일 및 기능 통합 리팩토링

frontend/src/business/Page/BusinessManagePage.jsx, frontend/src/pay/Component/Pay.jsx, frontend/src/pay/Component/PayList.jsx, frontend/src/pay/Form/PaymentForm.jsx, frontend/src/user/component/UserInfo.jsx, src/main/java/com/petservice/main/business/controller/ReservationController.java, src/main/java/com/petservice/main/business/database/repository/ReservationRepository.java, src/main/java/com/petservice/main/business/service/Interface/ReservationServiceInterface.java, src/main/java/com/petservice/main/business/service/ReservationService.java, src/main/java/com/petservice/main/payment/controller/PayController.java
예약, 결제 목록 조회에 페이징 기능 추가 하였으며, 결제 검증, 회원정보 관련 버그를 수정함
=> 페이징 기능 추가 및 오류 수정

frontend/src/business/Component/Reservation.jsx, frontend/src/business/Component/ReservationList.jsx, frontend/src/business/Page/BusinessManagePage.jsx, frontend/src/business/Page/UserReservationManagePage.jsx, frontend/src/common/Api/ApiService.jsx, frontend/src/pay/Component/Pay.jsx, frontend/src/pay/Component/PayList.jsx, frontend/src/pay/Form/PaymentForm.jsx, src/main/java/com/petservice/main/business/controller/PetBusinessController.java, src/main/java/com/petservice/main/business/controller/ReservationController.java, src/main/java/com/petservice/main/business/service/ReservationService.java, src/main/java/com/petservice/main/payment/controller/PayController.java
결제 취소가 정상적으로 처리되도록(사용자, 사업자 관리 화면에서) 로직 수정 및 결제, 예약관련 UI 개선
=> 결제 관련 오류 수정, UI 개선

frontend/src/user/Form/RegisterForm.jsx
=> 정산 계좌 기능 추가에 따른 후속 수정

frontend/src/review/Component/ReviewDeleteButton.jsx, frontend/src/review/Component/ReviewItem.jsx, frontend/src/review/Component/StarRating.jsx, frontend/src/review/Form/ReviewRegisterForm.jsx, frontend/src/review/Form/ReviewUpdateForm.jsx, frontend/src/review/Page/ReviewDetailPage.jsx, frontend/src/review/Page/ReviewListPage.jsx, src/main/java/com/petservice/main/business/database/entity/Reservation.java, src/main/java/com/petservice/main/review/controller/ReviewController.java, src/main/java/com/petservice/main/review/database/dto/ReviewDTO.java, src/main/java/com/petservice/main/review/database/mapper/ReviewMapper.java, src/main/java/com/petservice/main/review/database/repository/ReviewRepository.java, src/main/java/com/petservice/main/review/service/ReviewServiceImpl.java
=> feat: 리뷰 기능 개선

frontend/src/App.jsx, frontend/src/common/Api/Api.jsx, frontend/src/common/Api/ApiService.jsx, frontend/src/common/Ui/Pagination.jsx, frontend/src/review/Page/MyReviewListPage.jsx, frontend/src/review/Page/ReviewListPage.jsx, frontend/src/user/component/UserInfo.jsx, src/main/java/com/petservice/main/review/controller/ReviewController.java, src/main/java/com/petservice/main/review/database/repository/ReviewRepository.java, src/main/java/com/petservice/main/review/service/ReviewService.java, src/main/java/com/petservice/main/review/service/ReviewServiceImpl.java
=> 리뷰쪽 수정 (전체목록보기, 내리뷰보기)

frontend/src/pay/Form/PaymentForm.jsx
=> 결제 기능 오류 수정

frontend/src/qna/Component/AnswerList.jsx, frontend/src/review/Page/ReviewDetailPage.jsx, src/main/java/com/petservice/main/qna/service/post/QnaPostService.java, src/main/java/com/petservice/main/review/controller/ReviewController.java, src/main/java/com/petservice/main/review/service/ReviewService.java, src/main/java/com/petservice/main/review/service/ReviewServiceImpl.java
=> fix: 리뷰·QnA 오류수정

frontend/src/review/Component/StarRating.jsx
=> fix/star-rating UI

frontend/src/business/Page/BusinessSearchPage.jsx, src/main/java/com/petservice/main/bookmark/service/BookmarkServiceImpl.java, src/main/java/com/petservice/main/bookmark/service/BookmarkServiceInterface.java, src/main/java/com/petservice/main/business/database/repository/PetBusinessRepository.java, src/main/java/com/petservice/main/business/service/PetBusinessService.java, src/main/java/com/petservice/main/manage/service/ManagementService.java, src/main/java/com/petservice/main/qna/service/post/QnaPostService.java, src/main/java/com/petservice/main/user/database/repository/BookmarkRepository.java, src/main/java/com/petservice/main/user/service/UserService.java
북마크 삭제 로직 오류, 사업자 조회 관련 리포지토리 쿼리 오류 수정
=> 북마크, 사업자 검색 오류 수정
